# Data Cleaning

### 1. Setup
#### Importing the libraries needed for data loading, cleaning, and transformation.

In [3]:
##Package Import

import pandas as pd
import numpy as np
import datetime as dt

### 2. Load the Dataset
#### Reading the raw customer shopping behavior data and previewing the first few rows to get an initial sense of the structure.

In [4]:
#Loading the dataset using pandas

cust = pd.read_csv('customer_shopping_behavior_DATA.csv')
cust.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

### 2.1 Initial Exploration
#### Checking the number of unique values in each column to get a quick sense of which fields are categorical, which are near-continuous, and where potential data quality issues might be hiding.

In [6]:
cust.nunique()

Customer ID               3900
Age                         53
Gender                       2
Item Purchased              25
Category                     4
Purchase Amount (USD)       81
Location                    50
Size                         4
Color                       25
Season                       4
Review Rating               26
Subscription Status          2
Shipping Type                6
Discount Applied             2
Promo Code Used              2
Previous Purchases          50
Payment Method               6
Frequency of Purchases       7
dtype: int64

#### Viewing summary statistics for the numeric columns to spot any obvious outliers or inconsistencies.

In [17]:
cust.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

#### Checking data types and non-null counts for each column to identify missing values.

In [18]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

#### Checking for duplicate rows in the dataset.

In [19]:
cust.duplicated().sum()

np.int64(0)

### 3. Column Name Standardization
#### Cleaning up column headers — stripping whitespace, converting to lowercase, replacing spaces with underscores, and removing parentheses — so column names are consistent and easier to reference going forward.

In [20]:
#Renaming columns according to snake casing for better readability

cust = cust.rename(columns = lambda x: x.strip().lower().replace(' ','_').replace('(','').replace(')',''))
cust.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

### 4. Handling Missing Values
#### Checking and filling missing values

#### Filling missing `review_rating` values with the column mean

In [21]:
# Checking if missing data or null values are present in the dataset

cust.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount_usd        0
location                   0
size                       0
color                      0
season                     0
review_rating             37
subscription_status        0
shipping_type              0
discount_applied           0
promo_code_used            0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
dtype: int64

In [22]:
cust.review_rating = cust.review_rating.fillna(cust.review_rating.mean().round(2))

In [23]:
cust.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount_usd       0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

### 5. Removing Redundant Columns
#### Checking whether `discount_applied` and `promo_code_used` carry the same information by counting mismatches between them.

In [24]:
sum(cust['discount_applied'] != cust['promo_code_used'])

0

#### Since the two columns matched with zero mismatches, `discount_applied` is redundant and is dropped to avoid duplicate information.

In [25]:
#Dropping discount_applied column

cust.drop(columns='discount_applied', inplace=True)

### 6. Feature Engineering: Purchase Frequency
#### Viewing the unique categories in `frequency_of_purchases` before converting them into a numeric, analysis-friendly format.

In [26]:
cust.frequency_of_purchases.unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

#### Mapping each purchase frequency category to an approximate number of days (e.g. Weekly → 7, Monthly → 30, Annually → 365). This turns a categorical field into a numeric one that can be used directly in calculations and SQL queries later.

In [27]:
#Creating new column for purchase frequency in days

frequency_map = {'Fortnightly':14, 'Weekly':7, 'Annually':365, 'Quarterly':90, 'Bi-Weekly':14, 'Monthly':30, 'Every 3 Months':90}

cust['purchase_frequency_days'] = cust['frequency_of_purchases'].map(frequency_map)
cust.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,365

#### Renaming `previous_purchases` to `repeat_purchase` for clarity, since the column represents the count of prior purchases made by a customer.

In [28]:
#Renaming previous_purchases to repeat_purchase_count for better understanding

cust.rename(columns={'previous_purchases':'repeat_purchase_count'},inplace=True)

### 7. Feature Engineering: Age Groups
#### Checking the range of unique ages present in the data before binning them into groups.

In [29]:
cust.age.unique()

array([55, 19, 50, 21, 45, 46, 63, 27, 26, 57, 53, 30, 61, 65, 64, 25, 52,
       66, 31, 56, 18, 38, 54, 33, 36, 35, 29, 70, 69, 67, 20, 39, 42, 68,
       49, 59, 47, 40, 41, 48, 22, 24, 44, 37, 58, 32, 62, 51, 28, 43, 34,
       23, 60])

#### Creating an `age_group` column by binning ages into 5-year buckets (16–20, 21–25, etc.) and inserting it next to the `age` column. Age and age_group are kept as separate columns so both granular and grouped analysis remain possible downstream.

In [30]:
#Create a new column age_group

bins = [15,20,25,30,35,40,45,50,55,60,65,70]
labels = ['16-20','21-25','26-30','31-35','36-40','41-45','46-50','51-55','56-60','61-65','66-70']
age_group= pd.cut(cust.age,bins= bins, labels=labels)
cust.insert(1,'age_group', age_group)

#### Final preview of the cleaned dataset before exporting it for the SQL stage.

In [31]:
cust.head()

,customer_id,age_group,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,promo_code_used,repeat_purchase_count,payment_method,frequency_of_purchases,purchase_frequency_days
0,1,51-55,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,14
1,2,16-20,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,14
2,3,46-50,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,7
3,4,21-25,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,7
4,5,41-45,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,365

In [32]:
#Exporting the clean dataset to .csv
cust.to_csv(r"D:\02_Cleaned Data.csv",index=False)

## Summary

This notebook prepares the raw customer shopping behavior dataset (~3,900 rows) for downstream SQL and Power BI analysis. Key steps:

- **Explored** the raw data structure, data types, and missing values.
- **Standardized** column names to a consistent lowercase, underscore-separated format.
- **Imputed** missing `review_rating` values using the column mean.
- **Removed** the redundant `discount_applied` column after confirming it was identical to `promo_code_used`.
- **Engineered** a numeric `purchase_frequency_days` feature from the categorical `frequency_of_purchases` column.
- **Renamed** `previous_purchases` to `repeat_purchase` for clarity.
- **Engineered** an `age_group` feature by binning `age` into 5-year ranges, kept alongside the original `age` column.

The cleaned dataset is now ready to be loaded into SQL Server for the next stage of analysis.